### ISSUE TITLE
no more 1080p recently

### ISSUE THREAD

**Issue by TeeTeeHaa** [TheGoddessInari/netflix-1080p-firefox#19] opened 2021-05-19 18:24 UTC
Despite having this addon installed Netflix only gives me 720p videos in my Firefox 88.0.1 (64-bit) on Windows 7. Until some weeks ago I got 1080p videos with this setup. In addition the Netflix App on my XBox One gave and still gives me 1080p videos, so neither my Netflix plan nor my internet connection should be the problem.

**Comment by gnafrgb** [comment] 2021-05-21 12:38
same here. 
firefox 88.0.1 on win 10 20H2 
only get 720p and 2.0ch
i tested microsoft edge. it give me 1080p. 
so i guess it's the same situation like the opener.

**Comment by MrEden** [comment] 2021-05-21 14:04
According to [this issue](https://github.com/jangxx/netflix-1080p/issues/22#issuecomment-841680600) Netflix changed the URL of their CDN. The maintainer of the Chrome Extension added the URL to the Code (taken from [this comment](https://github.com/jangxx/netflix-1080p/issues/22#issuecomment-841824235)) which seems to have fixed the problem.

**Comment by TheGoddessInari** [comment] 2021-05-21 15:13
Thanks for the heads up! I'll make a new release today to fix this. Cheers.

**Comment by lu5jzz** [comment] 2021-05-22 16:52
Same here. In Ubuntu 20.04.2 whith firefox 88.0.1 running, not work anymore  "netflix-1080p-firefox" addon. Now I can see only in 720p in Netflix. Approximately 4 days ago.

**Comment by psymole** [comment] 2021-05-24 01:04
+1 on Ubuntu 21.04 | Firefox 88.0.1 | Netflix 1080p Version 1.15.3

**Comment by TheGoddessInari** [comment] 2021-05-25 16:27
Should be fixed with 1.16.0. Let me know if it's not. Apologies for the delay there.

**Comment by psymole** [comment] 2021-05-25 16:39
> Should be fixed with 1.16.0. Let me know if it's not. Apologies for the delay there.

Works perfectly now for me. No need to apologize, thanks for the effort!

**Comment by TeeTeeHaa** [comment] 2021-05-25 20:15
> Should be fixed with 1.16.0. Let me know if it's not. Apologies for the delay there.

Works for me. Thank you very much. :+1:

**Comment by lu5jzz** [comment] 2021-05-25 22:10
> Should be fixed with 1.16.0. Let me know if it's not. Apologies for the delay there.

Works good in Ubuntu 20.04.2 whith firefox 88.0.1
![Selection_001](https://user-images.githubusercontent.com/55055379/119575055-d023a480-bd8c-11eb-9bf7-cdfe47ed4e05.jpg)

**Comment by lu5jzz** [comment] 2021-05-25 22:14
> Should be fixed with 1.16.0. Let me know if it's not. Apologies for the delay there.

Thanks very much TheGoddessInari. Thanks very, very much from Argentina.

**Comment by michael-ziedalski** [comment] 2021-05-25 23:19
Just wanted to point out that, while following this thread, I noticed that as of today on my Mac 10.11.6 and Firefox ver. 78.4.1esr, netflix is still showing 1080p while using the old version of the addon _(cadmium-playercore at 6.0029.052.051)_.

On my side, the addon has been fully working this entire time.

**Comment by gnafrgb** [comment] 2021-05-26 06:16
> 
> 
> Should be fixed with 1.16.0. Let me know if it's not. Apologies for the delay there.

1080 and 5.1 works good on win 10 firefox 88.0.1
thank you very much.

**Comment by TheGoddessInari** [comment] 2021-05-26 19:37
> Just wanted to point out that, while following this thread, I noticed that as of today on my Mac 10.11.6 and Firefox ver. 78.4.1esr, netflix is still showing 1080p while using the old version of the addon _(cadmium-playercore at 6.0029.052.051)_.
> 
> On my side, the addon has been fully working this entire time.

I had the same thing, because it was still getting served over the old domain. It's not uncommon for different people to be placed into different A/B testing groups for big sites.

I'm grateful people were able to point out what the problem was because this is the type of thing that can unfortunately end up looking like somehow a problem with environment.

May have to look into adding some kind of diagnostic/debug toggle for if people get problems that are hard to reproduce what's going on, but I can't think of many other addons that do that well, either.

**Closed** 2021-05-27 14:02 UTC
