### ISSUE TITLE
Stopped doing 1080p

### ISSUE THREAD

**Issue by kroeckx** [TheGoddessInari/netflix-1080p-firefox#14] opened 2021-03-03 22:08 UTC
1080p was working for a very long time, but now everything seems to be 720p.

**Comment by Termuellinator** [comment] 2021-03-04 08:03
see https://github.com/TheGoddessInari/netflix-1080p-firefox/issues/13 (lower down, ignore the behaviour of the initial reporter ;) )

**Comment by TheGoddessInari** [comment] 2021-03-10 02:52
This is fixed in 1.15.3, and was a duplicate of #13 anyway.

**Closed by TheGoddessInari** 2021-03-10 02:52 UTC
